routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('about', 'AboutController@index')->name('about');
Route::get('causes', 'CauseController@index')->name('causes');
Route::get('donations', 'DonationController@index')->name('donations');
Route::get('gallery', 'GalleryController@index')->name('gallery');
// Route::get('events', 'EventController@index')->name('events');
Route::get('request-help', 'RequestHelpController@index')->name('request-help');
Route::get('contact', 'ContactController@index')->name('contact');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use App\Role;
use App\Traits\PersistsData;
use App\Http\Requests\PutUser;
use App\Http\Requests\PostUser;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class User extends Authenticatable
{
    use Notifiable, PersistsData;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The roles that belong to the User
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'role_users', 'user_id', 'role_id');
    }

    public function getFullnameAttribute()
    {
        return $this->first_name . " " . $this->last_name;;
    }

    public function getRoleAttribute()
    {
        return $this->roles()->first();
    }

    public function hasRole($role)
    {
        $roles = $this->roles()->pluck('name');

        return $roles->contains($role);
    }

    public static function persist(PostUser $request)
    {
        $user = null;
        $data = $request->validated();

        DB::transaction(function () use($user, $data) {
            $user = self::create([
                'first_name' => $data['first_name'],
                'last_name' => $data['last_name'],
                'email' => $data['email'],
                'password' => Hash::make($data['password']),
            ]);

            $user->roles()->attach($data['role_id']);
        });

        return $user;
    }

    public static function modify(PutUser $request, User $user)
    {
        $data = $request->validated();

        DB::transaction(function () use($user, $data) {
            $user->update([
                'first_name' => $data['first_name'],
                'last_name' => $data['last_name'],
                'email' => $data['email'],
                'password' => Hash::make($data['password']),
            ]);

            $user->roles()->sync([$data['role_id']]);
        });

        return $user;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostUser;
use App\Http\Requests\PutUser;
use App\Role;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');

        $this->authorizeResource(User::class, 'user');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $metaTitle = 'Users';
        $users = User::all();
        return view('users.index', compact('metaTitle','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $metaTitle = 'Add User';
        $roles = Role::all();
        return view('users.create', compact('metaTitle', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\PostUser  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostUser $request)
    {
        User::persist($request);

        return redirect()->back()->with([
            'status' => "User has been added."
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $metaTitle = 'Edit User';
        $roles = Role::all();
        return view('users.edit', compact('user', 'metaTitle', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\PutUser  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(PutUser $request, User $user)
    {
        $user = User::modify($request, $user);

        return redirect()->back()->with([
            'status' => "User has been updated."
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">
                        @isset($metaTitle)
                            {{ $metaTitle}}
                        @endisset
                    </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="{{ route('home') }}">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="{{ route('users.index') }}">Users</a>
                        </li>
                        <li class="breadcrumb-item active">{{ $metaTitle }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-12">
                    <!-- Custom tabs (Charts with tabs)-->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fas fa-users mr-1"></i>
                                @isset($metaTitle)
                                    {{ $metaTitle }}
                                @endisset
                            </h3>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            @include('partials.status')
                            <form action="{{ route('users.store') }}" method="post">
                                @csrf
                                <div class="form-group row">
                                    <div class="col-12">
                                        <input type="text" name="first_name" class="form-control @error('first_name') is-invalid @enderror" placeholder="First name" value="{{ old('first_name') }}">
                                    </div>

                                    @error('first_name')
                                        <div class="col-12">
                                            <small class="form-text text-danger">
                                            {{ $message }}
                                            </small>
                                        </div>
                                    @enderror
                                </div>

                                <div class="form-group row">
                                    <div class="col-12">
                                        <input type="text" name="last_name" class="form-control @error('last_name') is-invalid @enderror" placeholder="Last name" value="{{ old('last_name') }}">
                                    </div>

                                    @error('last_name')
                                        <div class="col-12">
                                            <small class="form-text text-danger">
                                            {{ $message }}
                                            </small>
                                        </div>
                                    @enderror
                                </div>

                                <div class="form-group row">
                                    <div class="col-12">
                                        <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email" value="{{ old('email') }}">
                                    </div>
                                    @error('email')
                                        <div class="col-12">
                                            <small class="form-text text-danger">
                                            {{ $message }}
                                            </small>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        <select class="form-control" name="role_id">
                                            <option>
                                                Select user's role
                                            </option>
                                            @foreach ($roles as $role)
                                                <option value="{{ $role->id }}" {{ old('role_id') === $role->id ? 'selected' : '' }}>
                                                    {{ $role->name }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>

                                    @error('role_id')
                                        <div class="col-12">
                                            <small class="form-text text-danger">
                                            {{ $message }}
                                            </small>
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <div class="col-12">
                                        <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password">
                                    </div>
                                    @error('password')
                                        <div class="col-12">
                                            <small class="form-text text-danger">
                                            {{ $message }}
                                            </small>
                                        </div>
                                    @enderror
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <button type="submit" class="btn btn-primary btn-block">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </section>
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">
                    @isset($metaTitle)
                        {{ $metaTitle}}
                    @endisset
                </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        <a href="{{ route('home') }}">Dashboard</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{{ route('users.index') }}">Users</a>
                    </li>
                    <li class="breadcrumb-item active">{{ $metaTitle }}</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<section class="content">
    <div class="container-fluid">
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <section class="col-lg-12">
                <!-- Custom tabs (Charts with tabs)-->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-users mr-1"></i>
                            @isset($metaTitle)
                                {{ $metaTitle }}
                            @endisset
                        </h3>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        @include('partials.status')
                        <form action="{{ route('users.update', $user->id) }}" method="post">
                            @csrf
                            @method('put')
                            <div class="form-group row">
                                <div class="col-12">
                                    <input type="text" name="first_name" class="form-control @error('first_name') is-invalid @enderror" placeholder="First name" value="{!! old('first_name', optional($user)->first_name) !!}">
                                </div>

                                @error('first_name')
                                    <div class="col-12">
                                        <small class="form-text text-danger">
                                        {{ $message }}
                                        </small>
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group row">
                                <div class="col-12">
                                    <input type="text" name="last_name" class="form-control @error('last_name') is-invalid @enderror" placeholder="Last name" value="{!! old('last_name', optional($user)->last_name) !!}">
                                </div>

                                @error('last_name')
                                    <div class="col-12">
                                        <small class="form-text text-danger">
                                        {{ $message }}
                                        </small>
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group row">
                                <div class="col-12">
                                    <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" placeholder="Email" value="{!! old('email', optional($user)->email) !!}">
                                </div>
                                @error('email')
                                    <div class="col-12">
                                        <small class="form-text text-danger">
                                        {{ $message }}
                                        </small>
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group row">
                                <div class="col-12">
                                    <select class="form-control" name="role_id">
                                        <option>
                                            Select user's role
                                        </option>
                                        @foreach ($roles as $role)
                                            @if (is_null($user->role))
                                                <option value="{{ $role->id }}" {{ old('role_id') === $role->id ? 'selected' : '' }}>
                                                    {{ $role->name }}
                                                </option>
                                            @else
                                                <option value="{{ $role->id }}" {{ $user->role->id === $role->id ? 'selected' : '' }}>
                                                    {{ $role->name }}
                                                </option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>

                                @error('role_id')
                                    <div class="col-12">
                                        <small class="form-text text-danger">
                                        {{ $message }}
                                        </small>
                                    </div>
                                @enderror
                            </div>
                            <div class="form-group row">
                                <div class="col-12">
                                    <input type="password" name="password" class="form-control @error('password') is-invalid @enderror" placeholder="Password">
                                </div>
                                @error('password')
                                    <div class="col-12">
                                        <small class="form-text text-danger">
                                        {{ $message }}
                                        </small>
                                    </div>
                                @enderror
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                                </div>
                            </div>
                        </form>
                    </div><!-- /.card-body -->
                </div>
                <!-- /.card -->
            </section>
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@push('styles')
    <link rel="stylesheet" href="{{ asset('adminlte-3/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css') }}">
@endpush
@section('content')

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">
                        @isset($metaTitle)
                            {{ $metaTitle}}
                        @endisset
                    </h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="{{ route('home') }}">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item active">{{ $metaTitle }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <!-- Main row -->
            <div class="row">
                <!-- Left col -->
                <section class="col-lg-12">
                    <!-- Custom tabs (Charts with tabs)-->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fas fa-users mr-1"></i>
                                @isset($metaTitle)
                                    {{ $metaTitle }}
                                @endisset
                            </h3>
                            <div class="card-tools">
                                <ul class="nav nav-pills ml-auto">
                                    <li class="nav-item">
                                        <a class="nav-link active text-center" title="Add user" href="{{ route('users.create') }}">
                                            <i class="fas fa-plus mr-1"></i>
                                            Add user
                                        </a>
                                    </li>
                                    {{-- <li class="nav-item">
                                        <a class="nav-link" href="#sales-chart" data-toggle="tab">Donut</a>
                                    </li> --}}
                                </ul>
                            </div>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <table class="table data-table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Role</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $user)
                                        <tr>
                                            <td scope="row">
                                                {{ $user->fullname}}
                                            </td>
                                            <td>
                                                {{ $user->email }}
                                            </td>
                                            <td>
                                                {{ $user->role->name }}
                                            </td>
                                            <td>
                                                <a title="Edit User" href="{{ route('users.edit', $user->id) }}" class="btn btn-primary">
                                                    <i class="fa fas fa-edit"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div><!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </section>
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
@endsection

@push('scripts')

    <script src="{{ asset('adminlte-3/assets/plugins/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('adminlte-3/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js') }}"></script>
    <script>
        $(document).ready(function () {
            $(".data-table").DataTable();
        })
    </script>

@endpush